development:
  adapter: postgresql
  encoding: unicode
  database: db_development
  host: localhost
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: db_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  encoding: unicode
  pool: 5
