development:
  adapter: postgresql
  encoding: utf8
  database: db_development
  host: localhost
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: db_test
  host: localhost
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  encoding: unicode
  pool: 5
