development:
  adapter: postgresql
  encoding: utf8
  database: db_development
  host: localhost
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: db_test
  host: localhost
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: db
  pool: 5
  username:
  password:
